### ISSUE TITLE
TUN режим для Android

### ISSUE THREAD

**Issue by NoahNour** [ClusterM/vpn-how-to#3]
Привет.
Есть такой вопрос. Я сделал всё по твоей доке, для fedora скачал nekoray, ключ подключение скопировал, всё ок. Жму подключение, вроде пишет, что подключен, но в морде VPN вижу статус offline. В итоге в nekoray включил режим TUN, подключился еще раз и всё заработало.
Для Android скачал предложенный тобой v2RayTun, скопировал ключ подключения, он все параметры видит, жму подключится, вроде пишет что всё ок, но инет на телефоне пропадает, а в морде vpn, опять же статус offline. Пробовал и v2rayNG и еще разные, ситуация повторяется. Нигде у них не нашел никакой настройки TUN или аналогичной.
Есть мысли, что не так?

**Comment by ClusterM** [comment]
Привет!
Не знаю даже. Странно, что статус "offline" пишется.

**Comment by NoahNour** [comment]
Проверил с другой мобилки, чтобы исключить свой телефон. Тоже самое. В логах нашел
`WARNING - XRAY: [2072018702] app/proxyman/inbound: connection ends > proxy/vless/inbound: fc9878f4-c8ed-4799-9758-2efdd658aba8 is not able to use xtls-rprx-vision`
это собственно id юзера с которого пытаюсь подключится.
Буду разбираться

**Comment by NoahNour** [comment]
Не пашет на версии Android 10 QKQ1.190825.002
